// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxLOrfqCkAUdq4a9bZR2ael7YR5ij5rr4',
    appId: '1:1055733223773:web:793345511da40141b058b4',
    messagingSenderId: '1055733223773',
    projectId: 'shuffle-a5a54',
    authDomain: 'shuffle-a5a54.firebaseapp.com',
    storageBucket: 'shuffle-a5a54.appspot.com',
    measurementId: 'G-943XCPJ7S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuXBr5-g1aerZLrdG_Apamp8K74hPUQJU',
    appId: '1:1055733223773:android:ec5642eec220f1c2b058b4',
    messagingSenderId: '1055733223773',
    projectId: 'shuffle-a5a54',
    storageBucket: 'shuffle-a5a54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT44wVgSXv2zfZgrr_YbIUH8NzoeK39_A',
    appId: '1:1055733223773:ios:ccdc2d1d33655929b058b4',
    messagingSenderId: '1055733223773',
    projectId: 'shuffle-a5a54',
    storageBucket: 'shuffle-a5a54.appspot.com',
    iosBundleId: 'com.app.pac4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT44wVgSXv2zfZgrr_YbIUH8NzoeK39_A',
    appId: '1:1055733223773:ios:225a03f85232dcbbb058b4',
    messagingSenderId: '1055733223773',
    projectId: 'shuffle-a5a54',
    storageBucket: 'shuffle-a5a54.appspot.com',
    iosBundleId: 'com.app.pac4.RunnerTests',
  );
}
